call_permission: relax call_permission validation
wazo-platform/wazo-confd pull request #210
Opened 2021-07-16 14:12 UTC by pc-m

this field is for display only there's no need for anything complex here

2021-07-19 17:09 UTC, fblackburn1 requested changes
Do you know why/history of unique constraint?
user import is broken, you need to find_by(tenant&name) and get_by(tenant&name)

2021-07-20 14:22 UTC, fblackburn1 commented on wazo_confd/plugins/call_permission/validator.py
> +    )
Helpers already exist to use tenant
https://github.com/wazo-platform/wazo-confd/blob/master/wazo_confd/plugins/skill/validator.py

2021-07-20 14:31 UTC, fblackburn1 commented on CHANGELOG.md
> +
Must be updated to be unique by tenant

2021-07-20 19:51 UTC, pc-m commented
recheck

2021-07-20 20:00 UTC, fblackburn1 approved these changes

2021-07-20 21:02 UTC, merged