WAZO-2193 confd add /sounds search/sort
wazo-platform/wazo-confd pull request #216
Opened 2021-09-02 13:25 UTC by ja0x

Also added a new endpoint /sounds/{category}/files to allow sorting/searching on category's files

2021-09-03 13:47 UTC, fblackburn1 requested changes
I rebased your branch to fix copyright and fix the double quote usage

Please add copyright git-hook to your workflow:
https://github.com/wazo-platform/xivo-tools/tree/master/git-hooks

Please respect the service/wazo style. In all our code we use single quote (maybe some exception) and black is configured to respect this rule:
https://github.com/wazo-platform/wazo-confd/blob/master/tox.ini#L32
Always use tox to run black to avoid this kind of issue
 
When I read the ticket, I don't see any mention to create a new endpoint .. Why adding this, if not needed?
Moreover, before adding new endpoint/feature, we have an entire workflow to pass. Particularly, an validate the new openapi spec. I don't see any discussion about this here. Because `files` in the url is implicitly intended to return binary object, not metadata

Please split your branch to extract this new endpoint

2021-09-08 13:51 UTC, fblackburn1 approved these changes
Thanks, don't hesitate to ask if you have question about my commits

2021-09-08 15:01 UTC, ja0x commented
recheck

2021-09-08 15:44 UTC, fblackburn1 approved these changes

2021-09-08 15:55 UTC, merged