WAZO-2488 Add exten to callfilter surrogate users
wazo-platform/wazo-confd pull request #218
Opened 2021-09-07 15:21 UTC by ja0x

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/138

2021-09-07 16:00 UTC, ja0x commented
recheck

2021-09-08 14:02 UTC, pc-m requested changes
Looks good, I've added some nitpicking comments about string formatting and I would like one more integration test where the bsfilter exten is disabled or not set.

You should also add the `exten` field to the open API spec and add a CHANGELOG entry for the change in CHANGELOG.md

2021-09-08 15:25 UTC, pc-m submitted a review, later dismissed

2021-09-08 16:01 UTC, fblackburn1 approved these changes

2021-09-08 16:40 UTC, merged