Pull request for WAZO-2750-purge-meeting-authorization
wazo-platform/wazo-confd pull request #259
Opened 2022-04-12 12:37 UTC by sduthil

## meeting authorizations: purge items older than 24h

## meeting purge: fix timezone

Why:

* datetime.utcnow() returns UTC time WITHOUT a timezone
* when comparing the database date with a timestamp without a
timezone, PGSQL does the comparison in the local time zone
* when comparing with both timezones, PGSQL applies the corresponding
offset before comparing

2022-04-14 12:21 UTC, fblackburn1 reviewed
What do you think about merging this script with purge-meetings and only add a flag `--authorizations-only` ? It will remove duplicate overhead

2022-04-14 13:57 UTC, fblackburn1 requested changes
Tests are missing
Depends-on: https://github.com/wazo-platform/xivo-dao/pull/172

2022-04-18 14:33 UTC, sduthil commented
I've added the test and merge the purge script with `wazo-confd-purge-meetings`. Thanks for the review!

2022-04-18 15:26 UTC, sduthil commented
recheck

2022-04-19 13:28 UTC, fblackburn1 approved these changes
IMHO a really not perfect but more readable way to write many context managers with black constraint:
https://github.com/wazo-platform/wazo-confd/blob/master/integration_tests/suite/base/test_extensions.py#L543-L550

2022-04-19 15:28 UTC, merged