Add middlewares for /users
wazo-platform/wazo-confd pull request #322
Opened 2022-11-14 22:40 UTC by xxbillouxx

2022-11-16 14:56 UTC, pc-m requested changes

2022-11-16 14:56 UTC, pc-m commented on wazo_confd/plugins/user/middleware.py
> +        if switchboards:
You don't need the `if` here since there's only a `for`. Otherwise you can remove the `or []` when popping switchboards

2022-11-16 14:56 UTC, pc-m commented on wazo_confd/plugins/user/middleware.py
> +            Session.expire(model)
Could we use `Session.expire(model, ['lines'])` here instead of expiring everything?

2022-11-16 14:56 UTC, pc-m commented on wazo_confd/plugins/user/schema.py
> +    id = fields.Integer(dump_only=True)
Most fields from the `incall` schema should be available here.
`preprocess_subroutine`, `greeting_sound`, `caller_id_mode`, `caller_id_name`, `description`

2022-11-16 14:56 UTC, pc-m commented on integration_tests/suite/base/test_user_import.py
> +    try:
You should move the `try` after assigning `user_uuid` otherwise the finally will fail adding noise to the test.

2022-11-16 20:09 UTC, pc-m commented
also api.yml and the changelog need to be modified

2022-11-18 16:59 UTC, xxbillouxx commented
recheck

2022-11-18 17:34 UTC, xxbillouxx commented
recheck

2022-11-18 18:42 UTC, xxbillouxx commented
recheck

2022-11-18 20:43 UTC, pc-m approved these changes

2022-11-22 16:06 UTC, xxbillouxx commented
recheck

2022-11-22 16:48 UTC, xxbillouxx commented
recheck

2022-11-22 17:38 UTC, merged