Enable update on user switchboards
wazo-platform/wazo-confd pull request #359
Opened 2023-01-25 18:05 UTC by xxbillouxx

2023-01-27 13:45 UTC, xxbillouxx commented
recheck

2023-02-14 01:19 UTC, pc-m requested changes

2023-02-14 01:19 UTC, pc-m commented on wazo_confd/plugins/switchboard_member/middleware.py
> +        Add a new user to the members of a switchboard.
Are you sure this comment is right?

2023-02-14 01:19 UTC, pc-m commented on wazo_confd/plugins/switchboard_member/middleware.py
> +        Add a new user to the members of a switchboard.
or maybe the name of the function should not be dissociate?

2023-02-14 01:19 UTC, pc-m commented on wazo_confd/plugins/user/resource.py
> +            recursive=request.args.get(
It's not the first time I see this line. It should be extracted to a function

2023-03-02 18:42 UTC, pc-m approved these changes

2023-03-02 19:10 UTC, merged