Enable update on user groups
wazo-platform/wazo-confd pull request #368
Opened 2023-02-09 20:28 UTC by xxbillouxx

2023-02-09 21:42 UTC, sduthil commented
recheck

2023-02-14 01:12 UTC, pc-m requested changes

2023-02-14 01:12 UTC, pc-m commented on wazo_confd/plugins/user/middleware.py
> +            if groups:
If the user is associated to a group and I want to remove all group associations with a PUT I would do
```javascript
{
"groups": [],
}
```
But that would not remove any of my current group associations

2023-02-14 18:16 UTC, pc-m approved these changes

2023-02-14 18:46 UTC, merged