Wazo 3330 voicemails records deletion
wazo-platform/wazo-confd pull request #415
Opened 2023-09-08 19:16 UTC by xxbillouxx

2023-09-08 19:46 UTC, xxbillouxx commented
recheck

2023-09-12 19:46 UTC, DrPyser requested changes

2023-09-12 19:46 UTC, DrPyser commented on wazo_confd/sync_db.py
> +    from wazo_confd.http_server import app
is it possible to put this import at module toplevel?

2023-09-12 19:46 UTC, DrPyser commented on wazo_confd/sync_db.py
> +        from wazo_confd import sysconfd
toplevel too?

2023-09-14 17:05 UTC, pc-m submitted a review, later dismissed

2023-09-15 21:34 UTC, DrPyser submitted a review, later dismissed

2023-09-18 20:46 UTC, xxbillouxx commented
recheck

2023-09-19 13:50 UTC, merged