Wazo 3350
wazo-platform/wazo-confd pull request #424
Opened 2023-10-20 14:47 UTC by xxbillouxx

Depends-on: https://github.com/wazo-platform/xivo-dao/pull/248

2023-10-24 13:55 UTC, DrPyser requested changes
https://github.com/wazo-platform/wazo-confd/blob/8204008a1f15b44f6ae04dda5a8ececa27d39a58/wazo_confd/plugins/skill/schema.py#L16
The schema field for category should be deleted if the API doesn't expose/support that field anymore.

2023-10-25 19:55 UTC, DrPyser requested changes
Could you update the CHANGELOG.md since this is a breaking change in the public API?

2023-10-26 13:17 UTC, xxbillouxx commented
> Could you update the CHANGELOG.md since this is a breaking change in the public API?

Are you ok with that: `the "agent skill" resource now has a no more "category" field` ?

2023-10-30 14:13 UTC, DrPyser commented on CHANGELOG.md
> +* the `agent skill` resource now has no more `category` field.
```suggestion
* the `agent skill` resource no longer has a `category` field.
```

2023-10-30 14:20 UTC, DrPyser submitted a review, later dismissed
Well done!

2023-10-30 17:16 UTC, DrPyser approved these changes

2023-10-30 17:39 UTC, merged