Add test to check concurrent get/create on tenant
wazo-platform/wazo-confd pull request #430
Opened 2023-11-07 16:00 UTC by xxbillouxx

Depends-On: https://github.com/wazo-platform/xivo-dao/pull/253

2023-11-17 21:32 UTC, sduthil requested changes

2023-11-17 21:32 UTC, sduthil commented on integration_tests/suite/base/test_contexts.py
> +        threads[i].join()
How about a nicer interface like [ThreadPoolExecutor](https://www.digitalocean.com/community/tutorials/how-to-use-threadpoolexecutor-in-python-3#step-2-using-threadpoolexecutor-to-execute-a-function-in-threads)?

2023-11-17 21:32 UTC, sduthil commented on integration_tests/suite/base/test_contexts.py
> +            )
IMHO, asserting for 500 status code is enough, we don't want *any* error to occur during this scenario.

2023-11-20 16:26 UTC, sduthil approved these changes

2023-11-20 16:33 UTC, sduthil commented
regate

2023-11-20 16:33 UTC, xxbillouxx commented
recheck

2023-11-20 17:21 UTC, merged